/**
 * pass 画像を base64 で src/pkpass/images.ts に書き出す。
 *   - logo.png / @2x / @3x : pass-logo/ の白反転ワードマークをそのまま埋め込む
 *   - icon.png / @2x / @3x : 紫紺(#262055)地に白い医療十字の正方形アイコンを生成
 *
 * icon は Wallet の必須ファイル。ワードマークは 29px 正方形では判読できないため、
 * アイコンにはクリニックらしい白十字マークを用いる(最終ブランドアイコンに差し替え可)。
 *
 * 依存なし(node:zlib のみ)。使い方: npm run gen:images
 */
import { deflateSync } from "node:zlib";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const workerDir = join(__dirname, "..");
const logoDir = join(workerDir, "..", "pass-logo");
const outFile = join(workerDir, "src", "pkpass", "images.ts");

const BG = [38, 32, 85]; // #262055 紫紺
const FG = [255, 255, 255]; // 白

// ---- 最小 PNG エンコーダ(RGBA, フィルタ none)----
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();
function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, "ascii");
  const crcBuf = Buffer.alloc(4);
  crcBuf.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([len, typeBuf, data, crcBuf]);
}
function encodePng(width, height, rgba) {
  const sig = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // color type RGBA
  ihdr[10] = 0;
  ihdr[11] = 0;
  ihdr[12] = 0;
  // 各行頭にフィルタバイト 0
  const stride = width * 4;
  const raw = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0;
    rgba.copy(raw, y * (stride + 1) + 1, y * stride, y * stride + stride);
  }
  const idat = deflateSync(raw, { level: 9 });
  return Buffer.concat([
    sig,
    chunk("IHDR", ihdr),
    chunk("IDAT", idat),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

// ---- 白十字アイコン生成 ----
function makeCrossIcon(size) {
  const rgba = Buffer.alloc(size * size * 4);
  // 背景
  for (let i = 0; i < size * size; i++) {
    rgba[i * 4] = BG[0];
    rgba[i * 4 + 1] = BG[1];
    rgba[i * 4 + 2] = BG[2];
    rgba[i * 4 + 3] = 255;
  }
  // 十字: 中央、腕の太さ ~26%、全長 ~64%
  const arm = Math.round(size * 0.26);
  const span = Math.round(size * 0.64);
  const c = size / 2;
  const half = span / 2;
  const t = arm / 2;
  const inV = { x0: c - t, x1: c + t, y0: c - half, y1: c + half };
  const inH = { x0: c - half, x1: c + half, y0: c - t, y1: c + t };
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const px = x + 0.5;
      const py = y + 0.5;
      const inVert = px >= inV.x0 && px < inV.x1 && py >= inV.y0 && py < inV.y1;
      const inHorz = px >= inH.x0 && px < inH.x1 && py >= inH.y0 && py < inH.y1;
      if (inVert || inHorz) {
        const o = (y * size + x) * 4;
        rgba[o] = FG[0];
        rgba[o + 1] = FG[1];
        rgba[o + 2] = FG[2];
        rgba[o + 3] = 255;
      }
    }
  }
  return encodePng(size, size, rgba);
}

async function main() {
  const entries = {};
  for (const name of ["logo.png", "logo@2x.png", "logo@3x.png"]) {
    entries[name] = (await readFile(join(logoDir, name))).toString("base64");
  }
  for (const [name, size] of [
    ["icon.png", 29],
    ["icon@2x.png", 58],
    ["icon@3x.png", 87],
  ]) {
    const buf = makeCrossIcon(size);
    entries[name] = buf.toString("base64");
    console.log(`generated ${name} (${size}x${size}, ${buf.length} bytes)`);
  }

  const body =
    `/**\n * AUTO-GENERATED by scripts/gen-images.mjs — 手で編集しない。\n` +
    ` * logo=ワードマーク(pass-logo/), icon=白十字の正方形。base64 埋め込み。\n */\n` +
    `export const PASS_IMAGES: Record<string, string> = {\n` +
    Object.entries(entries)
      .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
      .join("\n") +
    `\n};\n`;
  await writeFile(outFile, body, "utf8");
  console.log(`wrote ${outFile} (${Object.keys(entries).length} images)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
